# Generated by Django 6.0.3 on 2026-04-17 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carrito_itemcarrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=15, verbose_name='Cédula / RUC')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('metodo_envio', models.CharField(choices=[('TIENDA', 'Retiro en tienda'), ('DOMICILIO', 'Envío a domicilio')], default='TIENDA', max_length=20)),
                ('direccion_envio', models.TextField(blank=True, null=True, verbose_name='Dirección de Envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total a Pagar ($)')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False, verbose_name='¿Pago confirmado?')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al momento de la compra', max_digits=10)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.pedido')),
            ],
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
