# Generated by Django 6.0.3 on 2026-04-17 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pedido_remove_itemcarrito_carrito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Local')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('direccion', models.TextField(verbose_name='Dirección Exacta')),
                ('latitud', models.DecimalField(decimal_places=6, help_text='Ej: -0.180653', max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, help_text='Ej: -78.467834', max_digits=9)),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio ($)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Disponible'),
        ),
    ]
