# Generated by Django 6.0.3 on 2026-04-18 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tienda_alter_producto_precio_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='apellidos',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener letras.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener letras.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Teléfono'),
        ),
    ]
